# coding: utf-8

"""
    Openrouteservice

    This is the openrouteservice API documentation for ORS Core-Version 8.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).  # noqa: E501

    OpenAPI spec version: v2
    Contact: support@smartmobility.heigit.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest
import configparser

import openrouteservice as ors
from openrouteservice.api.pois_api import PoisApi  # noqa: E501
from openrouteservice.rest import ApiException


class TestPoisApi(unittest.TestCase):
    """PoisApi unit test stubs"""

    def setUp(self):
        cfg = configparser.ConfigParser()
        cfg.read('tests-config.ini')
        configuration = ors.Configuration()
        configuration.api_key['Authorization'] = cfg['ORS']['apiKey']
        self.api = PoisApi(ors.ApiClient(configuration))  # noqa: E501

    def tearDown(self):
        pass

    def test_pois_post(self):
        """Test case for pois_post

        Pois Service  # noqa: E501
        """

        body = ors.OpenpoiservicePoiRequest(
            request='pois',
            geometry=ors.PoisGeometry(
                bbox=[[8.8034,53.0756],[8.7834,53.0456]],
                geojson={"type":"Point","coordinates":[8.8034,53.0756]},
                buffer=200
            ),
            sortby='distance'
        )

        response = self.api.pois_post(body)
        self.assertIsNotNone(response)
        self.assertEqual(response.type, "FeatureCollection")

        body.filters = ors.PoisFilters(
            smoking=['yes']
        )

        response2 = self.api.pois_post(body)
        self.assertIsNotNone(response2)
        self.assertGreaterEqual(len(response.features), len(response2.features))

if __name__ == '__main__':
    unittest.main()
