# coding: utf-8

"""
    Openrouteservice

    This is the openrouteservice API documentation for ORS Core-Version 8.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).  # noqa: E501

    OpenAPI spec version: v2
    Contact: support@smartmobility.heigit.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest
import configparser

import openrouteservice
from openrouteservice.api.elevation_api import ElevationApi  # noqa: E501
from openrouteservice.rest import ApiException


class TestElevationApi(unittest.TestCase):
    """ElevationApi unit test stubs"""

    def setUp(self):
        cfg = configparser.ConfigParser()
        cfg.read('tests-config.ini')
        configuration = openrouteservice.Configuration()
        configuration.api_key['Authorization'] = cfg['ORS']['apiKey']
        self.api = ElevationApi(openrouteservice.ApiClient(configuration))  # noqa: E501

    def tearDown(self):
        pass

    def test_elevation_line_post(self):
        """Test case for elevation_line_post

        Elevation Line Service  # noqa: E501
        """
        body = openrouteservice.ElevationLineBody(
            format_in="encodedpolyline5",
            geometry="u`rgFswjpAKD"
        )
        response = self.api.elevation_line_post(body)
        self.assertEqual(response.geometry.coordinates[0], [13.3313, 38.10843, 72.0])

    def test_elevation_point_get(self):
        """Test case for elevation_point_get

        Elevation Point Service  # noqa: E501
        """
        response = self.api.elevation_point_get(geometry=[13.331273, 38.10849])
        self.assertEqual(response.geometry.coordinates, [13.331273,38.10849,72])

    def test_elevation_point_post(self):
        """Test case for elevation_point_post

        Elevation Point Service  # noqa: E501
        """
        body = openrouteservice.ElevationPointBody(
            format_in='point',
            geometry=[13.331273, 38.10849]
        )

        response = self.api.elevation_point_post(body)
        self.assertEqual(response.geometry.coordinates, [13.331273,38.10849,72])


if __name__ == '__main__':
    unittest.main()
