# coding: utf-8

"""
    Openrouteservice

    This is the openrouteservice API documentation for ORS Core-Version 8.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).  # noqa: E501

    OpenAPI spec version: v2
    Contact: support@smartmobility.heigit.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest
import configparser

import openrouteservice
from openrouteservice.api.geocode_api import GeocodeApi  # noqa: E501
from openrouteservice.rest import ApiException


class TestGeocodeApi(unittest.TestCase):
    """GeocodeApi unit test stubs"""

    def setUp(self):
        cfg = configparser.ConfigParser()
        cfg.read('tests-config.ini')
        configuration = openrouteservice.Configuration()
        configuration.api_key['Authorization'] = cfg['ORS']['apiKey']
        self.api = GeocodeApi(openrouteservice.ApiClient(configuration))  # noqa: E501

    def tearDown(self):
        pass

    def test_geocode_autocomplete_get(self):
        """Test case for geocode_autocomplete_get

        Geocode Autocomplete Service  # noqa: E501
        """
        text = "Toky"
        response = self.api.geocode_autocomplete_get(text)
        self.assertIsNotNone(response)
        self.assertEqual(len(response.features), 10)

    def test_geocode_reverse_get(self):
        """Test case for geocode_reverse_get

        Reverse Geocode Service  # noqa: E501
        """
        lon = 2.294471
        lat = 48.858268
        response = self.api.geocode_reverse_get(lon, lat)
        self.assertIsNotNone(response)
        self.assertEqual(len(response.features), 10)

    def test_geocode_search_get(self):
        """Test case for geocode_search_get

        Forward Geocode Service  # noqa: E501
        """
        text = "Namibian Brewery"
        response = self.api.geocode_search_get(text)
        self.assertIsNotNone(response)
        self.assertEqual(len(response.features), 10)

    def test_geocode_search_structured_get(self):
        """Test case for geocode_search_structured_get

        Structured Forward Geocode Service (beta)  # noqa: E501
        """
        response = self.api.geocode_search_structured_get(locality='Tokyo')
        self.assertIsNotNone(response)


if __name__ == '__main__':
    unittest.main()
