# coding: utf-8

"""
    Openrouteservice

    This is the openrouteservice API documentation for ORS Core-Version 8.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).  # noqa: E501

    OpenAPI spec version: v2
    Contact: support@smartmobility.heigit.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest
import configparser

import openrouteservice
from openrouteservice.api.directions_service_api import DirectionsServiceApi  # noqa: E501
from openrouteservice.rest import ApiException


class TestDirectionsServiceApi(unittest.TestCase):
    """DirectionsServiceApi unit test stubs"""

    def setUp(self):
        cfg = configparser.ConfigParser()
        cfg.read('tests-config.ini')
        configuration = openrouteservice.Configuration()
        configuration.api_key['Authorization'] = cfg['ORS']['apiKey']
        self.api = DirectionsServiceApi(openrouteservice.ApiClient(configuration))  # noqa: E501

    def tearDown(self):
        pass

    def test_get_geo_json_route(self):
        """Test case for get_geo_json_route

        Directions Service GeoJSON  # noqa: E501
        """
        body = openrouteservice.DirectionsService(
            coordinates=[[8.681495,49.41461],[8.686507,49.41943],[8.687872,49.420318]]
        )
        profile = 'driving-car'
        response = self.api.get_geo_json_route(body, profile)
        self.assertEqual(response.bbox, [8.681423, 49.414599, 8.690123, 49.420514])

    #def test_get_gpx_route(self):
    #    """Test case for get_gpx_route
    #
    #    Directions Service GPX  # noqa: E501
    #    """
    #    coordinates = [[8.681495,49.41461],[8.686507,49.41943],[8.687872,49.420318]]
    #    body = openrouteservice.DirectionsService1(
    #        coordinates=coordinates
    #    )
    #    profile = 'driving-car'
    #    response = self.api.get_gpx_route(body, profile)
    #    self.assertIsNotNone(response)

    def test_get_json_route(self):
        """Test case for get_json_route

        Directions Service JSON  # noqa: E501
        """
        body = openrouteservice.DirectionsService1(
            coordinates=[[8.681495,49.41461],[8.686507,49.41943],[8.687872,49.420318]]
        )
        profile = 'driving-car'
        response = self.api.get_json_route(body, profile)
        self.assertIsNotNone(response)


if __name__ == '__main__':
    unittest.main()
