# coding: utf-8

"""
    Openrouteservice

    This is the openrouteservice API documentation for ORS Core-Version 7.1.1. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).  # noqa: E501

    OpenAPI spec version: 7.1.1
    Contact: support@smartmobility.heigit.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest
import configparser

import openrouteservice
from openrouteservice.api.snapping_service_api import SnappingServiceApi  # noqa: E501
from openrouteservice.rest import ApiException
from openrouteservice import apiClient


class TestSnappingServiceApi(unittest.TestCase):
    """SnappingServiceApi unit test stubs"""

    def setUp(self):
        cfg = configparser.ConfigParser()
        cfg.read('tests-config.ini')
        self.api = SnappingServiceApi(apiClient(cfg['ORS']['apiKey']))  # noqa: E501

    def tearDown(self):
        pass

    def test_get_default(self):
        """Test case for get_default

        Snapping Service  # noqa: E501
        """
        # response = self.api.get_default()
        # self.assertIsNotNone(response)

    def test_get_geo_json_snapping(self):
        """Test case for get_geo_json_snapping

        Snapping Service GeoJSON  # noqa: E501
        """
        # response = self.api.get_geo_json_snapping()
        # self.assertIsNotNone(response)

    def test_get_json_snapping(self):
        """Test case for get_json_snapping

        Snapping Service JSON  # noqa: E501
        """
        # response = self.api.get_json_snapping()
        # self.assertIsNotNone(response)


if __name__ == '__main__':
    unittest.main()
