# coding: utf-8

"""
    Openrouteservice

    This is the openrouteservice API documentation for ORS Core-Version 8.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).  # noqa: E501

    OpenAPI spec version: v2
    Contact: support@smartmobility.heigit.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest
import configparser

import openrouteservice
from openrouteservice.api.matrix_service_api import MatrixServiceApi  # noqa: E501
from openrouteservice.rest import ApiException


class TestMatrixServiceApi(unittest.TestCase):
    """MatrixServiceApi unit test stubs"""

    def setUp(self):
        cfg = configparser.ConfigParser()
        cfg.read('tests-config.ini')
        configuration = openrouteservice.Configuration()
        configuration.api_key['Authorization'] = cfg['ORS']['apiKey']
        self.api = MatrixServiceApi(openrouteservice.ApiClient(configuration))  # noqa: E501

    def tearDown(self):
        pass

    def test_get_default(self):
        """Test case for get_default

        Matrix Service  # noqa: E501
        """
        body = openrouteservice.MatrixProfileBody(
            locations=[[9.70093,48.477473],[9.207916,49.153868],[37.573242,55.801281],[115.663757,38.106467]]
        )
        profile = 'driving-car' # str | Specifies the matrix profile.
        
        response = self.api.get_default(body, profile)
        self.assertEqual(len(response.destinations), 4)


if __name__ == '__main__':
    unittest.main()
