# coding: utf-8

"""
    Openrouteservice

    This is the openrouteservice API documentation for ORS Core-Version 7.1.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).  # noqa: E501

    OpenAPI spec version: 7.1.0
    Contact: support@smartmobility.heigit.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GeoJSONIsochronesResponseMetadataEngine(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'build_date': 'str',
        'graph_date': 'str',
        'version': 'str'
    }

    attribute_map = {
        'build_date': 'build_date',
        'graph_date': 'graph_date',
        'version': 'version'
    }

    def __init__(self, build_date=None, graph_date=None, version=None):  # noqa: E501
        """GeoJSONIsochronesResponseMetadataEngine - a model defined in Swagger"""  # noqa: E501
        self._build_date = None
        self._graph_date = None
        self._version = None
        self.discriminator = None
        if build_date is not None:
            self.build_date = build_date
        if graph_date is not None:
            self.graph_date = graph_date
        if version is not None:
            self.version = version

    @property
    def build_date(self):
        """Gets the build_date of this GeoJSONIsochronesResponseMetadataEngine.  # noqa: E501

        The date that the service was last updated  # noqa: E501

        :return: The build_date of this GeoJSONIsochronesResponseMetadataEngine.  # noqa: E501
        :rtype: str
        """
        return self._build_date

    @build_date.setter
    def build_date(self, build_date):
        """Sets the build_date of this GeoJSONIsochronesResponseMetadataEngine.

        The date that the service was last updated  # noqa: E501

        :param build_date: The build_date of this GeoJSONIsochronesResponseMetadataEngine.  # noqa: E501
        :type: str
        """

        self._build_date = build_date

    @property
    def graph_date(self):
        """Gets the graph_date of this GeoJSONIsochronesResponseMetadataEngine.  # noqa: E501

        The date that the graph data was last updated  # noqa: E501

        :return: The graph_date of this GeoJSONIsochronesResponseMetadataEngine.  # noqa: E501
        :rtype: str
        """
        return self._graph_date

    @graph_date.setter
    def graph_date(self, graph_date):
        """Sets the graph_date of this GeoJSONIsochronesResponseMetadataEngine.

        The date that the graph data was last updated  # noqa: E501

        :param graph_date: The graph_date of this GeoJSONIsochronesResponseMetadataEngine.  # noqa: E501
        :type: str
        """

        self._graph_date = graph_date

    @property
    def version(self):
        """Gets the version of this GeoJSONIsochronesResponseMetadataEngine.  # noqa: E501

        The backend version of the openrouteservice that was queried  # noqa: E501

        :return: The version of this GeoJSONIsochronesResponseMetadataEngine.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this GeoJSONIsochronesResponseMetadataEngine.

        The backend version of the openrouteservice that was queried  # noqa: E501

        :param version: The version of this GeoJSONIsochronesResponseMetadataEngine.  # noqa: E501
        :type: str
        """

        self._version = version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GeoJSONIsochronesResponseMetadataEngine, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GeoJSONIsochronesResponseMetadataEngine):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
