# coding: utf-8

"""
    Openrouteservice

    This is the openrouteservice API documentation for ORS Core-Version 7.1.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).  # noqa: E501

    OpenAPI spec version: 7.1.0
    Contact: support@smartmobility.heigit.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GeoJSONPropertiesObjectCategoryIdsCategoryId(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'category_group': 'float',
        'category_name': 'str'
    }

    attribute_map = {
        'category_group': 'category_group',
        'category_name': 'category_name'
    }

    def __init__(self, category_group=None, category_name=None):  # noqa: E501
        """GeoJSONPropertiesObjectCategoryIdsCategoryId - a model defined in Swagger"""  # noqa: E501
        self._category_group = None
        self._category_name = None
        self.discriminator = None
        if category_group is not None:
            self.category_group = category_group
        if category_name is not None:
            self.category_name = category_name

    @property
    def category_group(self):
        """Gets the category_group of this GeoJSONPropertiesObjectCategoryIdsCategoryId.  # noqa: E501


        :return: The category_group of this GeoJSONPropertiesObjectCategoryIdsCategoryId.  # noqa: E501
        :rtype: float
        """
        return self._category_group

    @category_group.setter
    def category_group(self, category_group):
        """Sets the category_group of this GeoJSONPropertiesObjectCategoryIdsCategoryId.


        :param category_group: The category_group of this GeoJSONPropertiesObjectCategoryIdsCategoryId.  # noqa: E501
        :type: float
        """

        self._category_group = category_group

    @property
    def category_name(self):
        """Gets the category_name of this GeoJSONPropertiesObjectCategoryIdsCategoryId.  # noqa: E501


        :return: The category_name of this GeoJSONPropertiesObjectCategoryIdsCategoryId.  # noqa: E501
        :rtype: str
        """
        return self._category_name

    @category_name.setter
    def category_name(self, category_name):
        """Sets the category_name of this GeoJSONPropertiesObjectCategoryIdsCategoryId.


        :param category_name: The category_name of this GeoJSONPropertiesObjectCategoryIdsCategoryId.  # noqa: E501
        :type: str
        """

        self._category_name = category_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GeoJSONPropertiesObjectCategoryIdsCategoryId, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GeoJSONPropertiesObjectCategoryIdsCategoryId):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
