# coding: utf-8

"""
    Openrouteservice

    This is the openrouteservice API documentation for ORS Core-Version 7.1.1. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).  # noqa: E501

    OpenAPI spec version: 7.1.1
    Contact: support@smartmobility.heigit.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GeoJSONFeaturesObject(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'feature_properties': 'GeoJSONPropertiesObject',
        'geometry': 'GeoJSONGeometryObject',
        'type': 'str'
    }

    attribute_map = {
        'feature_properties': 'feature_properties',
        'geometry': 'geometry',
        'type': 'type'
    }

    def __init__(self, feature_properties=None, geometry=None, type='Feature'):  # noqa: E501
        """GeoJSONFeaturesObject - a model defined in Swagger"""  # noqa: E501
        self._feature_properties = None
        self._geometry = None
        self._type = None
        self.discriminator = None
        if feature_properties is not None:
            self.feature_properties = feature_properties
        if geometry is not None:
            self.geometry = geometry
        if type is not None:
            self.type = type

    @property
    def feature_properties(self):
        """Gets the feature_properties of this GeoJSONFeaturesObject.  # noqa: E501


        :return: The feature_properties of this GeoJSONFeaturesObject.  # noqa: E501
        :rtype: GeoJSONPropertiesObject
        """
        return self._feature_properties

    @feature_properties.setter
    def feature_properties(self, feature_properties):
        """Sets the feature_properties of this GeoJSONFeaturesObject.


        :param feature_properties: The feature_properties of this GeoJSONFeaturesObject.  # noqa: E501
        :type: GeoJSONPropertiesObject
        """

        self._feature_properties = feature_properties

    @property
    def geometry(self):
        """Gets the geometry of this GeoJSONFeaturesObject.  # noqa: E501


        :return: The geometry of this GeoJSONFeaturesObject.  # noqa: E501
        :rtype: GeoJSONGeometryObject
        """
        return self._geometry

    @geometry.setter
    def geometry(self, geometry):
        """Sets the geometry of this GeoJSONFeaturesObject.


        :param geometry: The geometry of this GeoJSONFeaturesObject.  # noqa: E501
        :type: GeoJSONGeometryObject
        """

        self._geometry = geometry

    @property
    def type(self):
        """Gets the type of this GeoJSONFeaturesObject.  # noqa: E501


        :return: The type of this GeoJSONFeaturesObject.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this GeoJSONFeaturesObject.


        :param type: The type of this GeoJSONFeaturesObject.  # noqa: E501
        :type: str
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GeoJSONFeaturesObject, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GeoJSONFeaturesObject):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
