# coding: utf-8

"""
    Openrouteservice

    This is the openrouteservice API documentation for ORS Core-Version 7.1.1. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).  # noqa: E501

    OpenAPI spec version: 7.1.1
    Contact: support@smartmobility.heigit.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class JSONStepManeuver(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'bearing_after': 'int',
        'bearing_before': 'int',
        'location': 'list[float]'
    }

    attribute_map = {
        'bearing_after': 'bearing_after',
        'bearing_before': 'bearing_before',
        'location': 'location'
    }

    def __init__(self, bearing_after=None, bearing_before=None, location=None):  # noqa: E501
        """JSONStepManeuver - a model defined in Swagger"""  # noqa: E501
        self._bearing_after = None
        self._bearing_before = None
        self._location = None
        self.discriminator = None
        if bearing_after is not None:
            self.bearing_after = bearing_after
        if bearing_before is not None:
            self.bearing_before = bearing_before
        if location is not None:
            self.location = location

    @property
    def bearing_after(self):
        """Gets the bearing_after of this JSONStepManeuver.  # noqa: E501

        The azimuth angle (in degrees) of the direction right after the maneuver.  # noqa: E501

        :return: The bearing_after of this JSONStepManeuver.  # noqa: E501
        :rtype: int
        """
        return self._bearing_after

    @bearing_after.setter
    def bearing_after(self, bearing_after):
        """Sets the bearing_after of this JSONStepManeuver.

        The azimuth angle (in degrees) of the direction right after the maneuver.  # noqa: E501

        :param bearing_after: The bearing_after of this JSONStepManeuver.  # noqa: E501
        :type: int
        """

        self._bearing_after = bearing_after

    @property
    def bearing_before(self):
        """Gets the bearing_before of this JSONStepManeuver.  # noqa: E501

        The azimuth angle (in degrees) of the direction right before the maneuver.  # noqa: E501

        :return: The bearing_before of this JSONStepManeuver.  # noqa: E501
        :rtype: int
        """
        return self._bearing_before

    @bearing_before.setter
    def bearing_before(self, bearing_before):
        """Sets the bearing_before of this JSONStepManeuver.

        The azimuth angle (in degrees) of the direction right before the maneuver.  # noqa: E501

        :param bearing_before: The bearing_before of this JSONStepManeuver.  # noqa: E501
        :type: int
        """

        self._bearing_before = bearing_before

    @property
    def location(self):
        """Gets the location of this JSONStepManeuver.  # noqa: E501

        The coordinate of the point where a maneuver takes place.  # noqa: E501

        :return: The location of this JSONStepManeuver.  # noqa: E501
        :rtype: list[float]
        """
        return self._location

    @location.setter
    def location(self, location):
        """Sets the location of this JSONStepManeuver.

        The coordinate of the point where a maneuver takes place.  # noqa: E501

        :param location: The location of this JSONStepManeuver.  # noqa: E501
        :type: list[float]
        """

        self._location = location

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(JSONStepManeuver, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JSONStepManeuver):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
