package:
  name: "{{ OPENROUTESERVICE_NAME|lower }}"
  version: "{{ OPENROUTESERVICE_VERSION }}"

source:
  git_url: https://github.com/GIScience/openrouteservice-py.git
  git_rev: "v{{ OPENROUTESERVICE_VERSION }}"


requirements:
  build:
    - python>=2.7,<2.8,>=3.6,<4.0
    - pip
    - requests>=2.0
    - responses>=0.10
    - conda-verify
    - coverage>=^5.4
  run:
    - python>=2.7,<2.8,>=3.6,<4.0
    - requests>=2.0
    - responses>=0.10
test:
  imports:
    - openrouteservice
  source_files:
    - openrouteservice
    - test
  requires:
    - pytest>1.0
    - requests>=2.0
    - responses>=0.10
    - coverage>=4.5.0
    - conda-verify
    - pytest-cov>=2.0.0
  commands:
    - pytest -x --cov=openrouteservice --cov-config=.coveragerc

about:
  home: https://github.com/GIScience/openrouteservice-py
  license: Apache
  license_family: BSD
  license_file: LICENSE
