{% set name = "openrouteservice" %}
{% set version = "2.3.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/GIScience/openrouteservice-py.git
  git_rev: "v{{ version }}"


requirements:
  build:
    - python>=3.4
    - pip
    - requests>=2.0
    - nose>=1.0
    - responses>=0.10
    - coveralls>=1.7.0
    - coverage>=4.5.0
  run:
    - requests>=2.0
test:
  imports:
    - openrouteservice
  source_files:
    - openrouteservice
    - test
  requires:
    - nose>1.0
    - requests>=2.0
    - responses>=0.10
    - coveralls>=1.7.0
    - coverage>=4.5.0
  commands:
    - nosetests -v

about:
  home: https://github.com/GIScience/openrouteservice-py
  license: Apache
  license_family: BSD
  license_file: LICENSE