name: tests

on:
  push:
    branches: ['**']

jobs:
  pytest:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10", "3.11", "pypy3.8", "pypy3.9" ]
        poetry-version: [ "1.5.1" ]
        os: [ ubuntu-20.04, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    name: Python ${{ matrix.python-version }} / Poetry ${{ matrix.poetry-version }} / ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install test dependencies
        run: pip install -r test-requirements.txt
      - name: Install tox
        run: pip install tox
      - name: Setup API Key
        env:
          ORS_API_KEY: ${{ secrets.ORS_API_KEY }}
        run: printf "[ORS]\napiKey = $ORS_API_KEY\n" > tests-config.ini
      - name: Run tests
        run: python -m tox
