name: Python package
on:
  pull_request:
    branches: '**'
  push:
    branches:
      - master
jobs:
  build-and-publish:
    name: Build and publish Python distributions 📦 to PyPI and TestPyPI
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up base Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Python Poetry Action
        uses: abatilo/actions-poetry@v2.1.0
        with:
          poetry-version: 1.1.4
      - name: Poetry install and test
        run: |
          pip install tox pytest pytest-cov
          poetry run tox -e py37
      - name: Publish distribution 📦 with dry-run
        run: |
          poetry install --no-dev
          poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
          poetry build
          poetry publish --dry-run
      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags')
        run: |
          poetry install --no-dev
          poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
          poetry build
          poetry publish
